version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      runtime-dependencies:
        patterns:
          - "com.github.jknack:handlebars:*"
          - "net.sourceforge.plantuml:plantuml-mit:*"
          - "org.jetbrains.kotlinx:kotlinx-coroutines-core:*"
          - "org.jetbrains.kotlin.jvm:*"
